- menu_name: "Serveis"

- name: "Contacte"
  url: "/contacte/"
  title: "Contacte"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscriure al RSS Feed"

- name: "Atom"
  url: "/atom.xml"
  title: "Subscriure al Atom Feed"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap per les eines Google Webmaster"
